'''			Problem 29: Distinct Powers

	How many distinct terms are in the sequence 
	generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

'''

'''
Solution: First, determine which numbers within range
		  are powers of another number within range.

			Ex: 2^2 = 4, 10^10 = 100

		  This gives us 12 numbers: 4, 8, 16, 32, 64,
		  9, 27, 81, 25, 36, 49, 100. These numbers 
		  will create duplicate terms in the sequence,
		  thus we must deal with them separately and 
		  subtract the number of duplicates from the
		  maximum number of terms.

		  Answer = max - duplicates
			
		  Max = 99 * 99 

		  For 4, there are 49 duplicates because 2^100 = 4^50.
		  The same applies to 9, 25, 36, 49, 100 for 3,5,6,7 and
		  10 respectively. 

		  Duplicates = 6 * 49 + other 

		  For 8, there are 32 duplicates between 2^2 and 2^99 
		  (2^99 = 8^33). Then, 4^99 = 8^66 and the duplicates
		  go from 34 to 66 (even), thus there are 17 more 
		  duplicates. 32 + 17 = 49 The same applies to 27.
			
		  Duplicates = 6*49 + 2*49 + other 
	  
		  For 16, there are 49 duplicates to 4^100. Then,
		  duplicates go in a pattern of 3 to 8^75. Thus,
		  from 51 - 75 you get 9 duplicates. 49 + 9 = 58
		  The same applies for 81.

		  Duplicates = 6*49 + 2*49 + 2*58 + other 

		  For 32:

		  (1/5) 2^100 = 32^20   (2-20 -- 19 duplicates)
		  (2/5) 4^100 = 32^40   (22-40 even -- 10 duplicates)
		  (3/5) 8^100 = 32^60   (21-60, multiples of 3 -- excluding the above -- 11 duplicates)
		  (4/5) 16^100 = 32^80  (44-80, multiples of 4 -- excluding the above -- 8 duplicates)

		  19 + 10 + 11 + 8 = 48

		  Duplicates = 6*49 + 2*49 + 2*58 + 48 + other 

		  For 64, there are 49 duplicates for when 8^100. 

		  (2/3) 16^99 = 64^66 ( 52-66 even -- 8 duplicates)
		  (5/6) 32^99 = 64^80 ( 55-80, multiples of 5 -- excluding the above -- 5 duplicates)

		  49 + 8 + 5 = 62

		  Duplicates = 6*49 + 2*49 + 2*58 + 48 + 62

'''
maximum = 99 * 99
duplicates = 6 * 49 + 2 * 49 + 2* 58 + 48 + 62
print(maximum - duplicates)
